# Generated by Django 5.2.6 on 2025-09-28 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auths', '0002_remove_account_roles_account_roles'),
    ]

    operations = [
        migrations.CreateModel(
            name='MenuItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre')),
                ('url', models.CharField(max_length=200, verbose_name='URL')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Ordén')),
                ('is_active', models.BooleanField(default=True)),
                ('roles', models.ManyToManyField(to='auths.role', verbose_name='Roles')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
