# Generated by Django 5.2.6 on 2025-09-28 02:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auths', '0002_remove_account_roles_account_roles'),
        ('menu', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menuitem',
            name='roles',
            field=models.ManyToManyField(blank=True, to='auths.role', verbose_name='Roles'),
        ),
    ]
