# Generated by Django 5.2.6 on 2025-09-28 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auths', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='roles',
        ),
        migrations.AddField(
            model_name='account',
            name='roles',
            field=models.ManyToManyField(to='auths.role', verbose_name='Rol'),
        ),
    ]
