# Generated by Django 5.2.6 on 2025-09-28 21:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auths', '0002_remove_account_roles_account_roles'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='status',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='auths.statusaccount', verbose_name='Estado'),
        ),
    ]
