# Generated by Django 5.2.6 on 2025-09-30 19:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auths', '0003_alter_account_status'),
        ('base', '0006_alter_company_options_remove_company_admin'),
    ]

    operations = [
        migrations.RenameField(
            model_name='account',
            old_name='roles',
            new_name='rol',
        ),
        migrations.AddField(
            model_name='account',
            name='company',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='accounts', to='base.company', verbose_name='Compañia'),
        ),
    ]
