# Generated by Django 5.2.6 on 2025-09-30 19:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auths', '0004_rename_roles_account_rol_account_company'),
        ('base', '0007_company_short_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='accounts', to='base.company', verbose_name='Compañia'),
        ),
    ]
