# Generated by Django 5.2.6 on 2025-09-27 21:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(blank=True, unique=True, verbose_name='Codigo')),
                ('img_invoice', models.ImageField(upload_to='', verbose_name='Imagen de la factura')),
                ('created_by', models.CharField(verbose_name='Creado por')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creacion')),
                ('updated_by', models.CharField(verbose_name='Actualizado por')),
                ('updated_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de actualizacion')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='base.client', verbose_name='Cliente')),
            ],
            options={
                'verbose_name': 'Factura',
                'verbose_name_plural': 'Facturas',
                'ordering': ['-created_at'],
            },
        ),
    ]
