# Generated by Django 5.2.6 on 2025-09-30 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='updated_by',
            field=models.CharField(blank=True, null=True, verbose_name='Actualizado por'),
        ),
    ]
