# Generated by Django 5.2.6 on 2025-10-01 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0002_alter_invoice_updated_by'),
    ]

    operations = [
        migrations.CreateModel(
            name='TypeInvoice',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(verbose_name='Nombre')),
                ('description', models.CharField(verbose_name='Descripcion')),
            ],
            options={
                'verbose_name': 'Concepto de Factura',
                'verbose_name_plural': 'Conceptos de Factura',
                'ordering': ['name'],
            },
        ),
    ]
