# Generated by Django 5.2.6 on 2025-10-01 03:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0003_typeinvoice'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='invoice.typeinvoice', verbose_name='Concepto de la factura'),
            preserve_default=False,
        ),
    ]
