# Generated by Django 5.2.7 on 2025-10-10 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0004_invoice_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='img_invoice',
            field=models.ImageField(upload_to='invoices/', verbose_name='Imagen de la factura'),
        ),
    ]
