# Generated by Django 5.2.6 on 2025-09-27 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, verbose_name='Nombre')),
                ('last_names', models.CharField(blank=True, verbose_name='Apellidos')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Correo electronico')),
                ('phone_number', models.CharField(unique=True, verbose_name='Numero de celular')),
                ('created_by', models.CharField(verbose_name='Creado por')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creacion')),
                ('updated_by', models.CharField(verbose_name='Actualizado por')),
                ('updated_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de actualizacion')),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
                'ordering': ['-created_at'],
            },
        ),
    ]
