# Generated by Django 5.2.6 on 2025-09-30 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_company'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='updated_by',
            field=models.CharField(blank=True, verbose_name='Actualizado por'),
        ),
    ]
