# Generated by Django 5.2.6 on 2025-09-30 19:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_alter_company_admin_alter_company_updated_by'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='company',
            options={'ordering': ['name'], 'verbose_name': 'Compañia', 'verbose_name_plural': 'Compañias'},
        ),
        migrations.RemoveField(
            model_name='company',
            name='admin',
        ),
    ]
