# Generated by Django 5.2.6 on 2025-09-30 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_alter_company_options_remove_company_admin'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='short_name',
            field=models.CharField(default='Sigimall', verbose_name='Nombre corto'),
            preserve_default=False,
        ),
    ]
